dist: xenial
language: ruby
rvm: 2.6.3
gemfile:
  - Gemfile
  - test/gemfiles/activesupport52.gemfile
  - test/gemfiles/activesupport51.gemfile
  - test/gemfiles/activesupport50.gemfile
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
